cc_test(
    name = "protocol_response",
    srcs = [
        "protocol_response_test.cc",
    ],
    deps = [
        "//Maman14/Server/protocol:libProtocolResponse",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "bytearray",
    srcs = [
        "bytearray_test.cc",
    ],
    deps = [
        "//Maman14/Server:libBytearray",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "user_backup_directory",
    srcs = [
        "user_backup_directory_test.cc",
    ],
    deps = [
        "//Maman14/Server:libUserBackupDirectory",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "backup_directory_manager",
    srcs = [
        "backup_directory_manager_test.cc",
    ],
    deps = [
        "//Maman14/Server:libBackupDirectoryManager",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "request_parser",
    srcs = [
        "request_parser_test.cc",
    ],
    deps = [
        "//Maman14/Server:libRequestParser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "request_reader",
    srcs = [
        "request_reader_test.cc",
    ],
    deps = [
        "//Maman14/Server:libRequestReader",
        "@com_google_googletest//:gtest_main",
    ],
)
