py_library(
    name = "server_message",
    srcs = ["server_message.py"],
    visibility = [
        "//Maman15/Server/backup_server:__pkg__",
        "//Maman15/Server/test:__pkg__",
    ],
)

py_library(
    name = "client_message",
    srcs = ["client_message.py"],
    visibility = [
        "//Maman15/Server/backup_server:__pkg__",
        "//Maman15/Server/test:__pkg__",
    ],
)
