cc_library(
    name = "private_key_wrapper",
    srcs = ["private_key_wrapper.cpp"],
    hdrs = ["private_key_wrapper.h"],
    visibility = [
        "//Maman15/Client:__pkg__",
        "//Maman15/Client/test:__pkg__",
    ],
    deps = [
        "@cryptopp",
    ],
)

cc_library(
    name = "aes_wrapper",
    srcs = ["aes_wrapper.cpp"],
    hdrs = ["aes_wrapper.h"],
    visibility = [
        "//Maman15/Client:__pkg__",
        "//Maman15/Client/test:__pkg__",
    ],
    deps = [
        "@cryptopp",
    ],
)
