load("test_defs.bzl", "py_server_test")

py_server_test(
    name = "test_server_message",
    srcs = [
        "test_server_message.py",
    ],
    deps = ["//Maman15/Server/server:server_message"],
)
