load("test_defs.bzl", "py_server_test")

py_server_test(
    name = "test_server_message",
    srcs = [
        "test_server_message.py",
    ],
    deps = ["//Maman15/Server/server:server_message"],
)

py_server_test(
    name = "test_port_info",
    srcs = [
        "test_port_info.py",
    ],
    deps = ["//Maman15/Server/server:port_info"],
)

py_server_test(
    name = "test_crc32",
    srcs = [
        "test_crc32.py",
    ],
    deps = ["//Maman15/Server/server:crc32"],
)
