py_library(
    name = "server_message",
    srcs = ["server_message.py"],
    visibility = [
        "//Maman15/Server/test:__pkg__",
    ],
)

py_library(
    name = "port_info",
    srcs = ["port_info.py"],
    visibility = [
        "//Maman15/Server/test:__pkg__",
    ],
)
