

py_library(
    name = "port_info",
    srcs = ["port_info.py"],
    visibility = [
        "//Maman15/Server/test:__pkg__",
    ],
)

py_library(
    name = "crc32",
    srcs = ["crc32.py"],
    visibility = [
        "//Maman15/Server/test:__pkg__",
    ],
)

py_library(
    name = "model",
    srcs = ["server_model.py"],
    visibility = [
        "//Maman15/Server/test:__pkg__",
    ],
)
