load("test_defs.bzl", "backup_client_test")

backup_client_test(
    name = "server_info_test",
    srcs = [
        "server_info_test.py",
        "//Maman14/Client/backup_client:server_info_srcs",
    ],
)

backup_client_test(
    name = "backup_info_test",
    srcs = [
        "backup_info_test.py",
        "//Maman14/Client/backup_client:backup_info_srcs",
    ],
)
