cc_test(
    name = "media-tests",
    srcs = [
        "media-test.cc",
        "//Maman11/USocial:media_files",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "user-test",
    srcs = [
        "user-test.cc",
        "//Maman11/USocial:common_files",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ]
)

cc_test(
    name = "post-test",
    srcs = [
        "post-test.cc",
        "//Maman11/USocial:post_files",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ]
)

cc_test(
    name = "usocial-test",
    srcs = [
        "usocial-test.cc",
        "//Maman11/USocial:common_files",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ]
)

# test_suite(
#     name = "all",
#     tests = [
#         "usocial-test"
#     ]
# )
