name: Maman15

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }} 
    steps:
      - name: Bazel cache
        uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}

      - uses: actions/checkout@v2

      - name: Test client
        run: bazel test //Maman15/Client/test:all --config=github_gcc --test_output=errors --test_summary=short

      - name: Test server
        run: bazel test //Maman15/Server/test:all --config=github_gcc --test_output=errors --test_summary=short
