name: Maman15

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
    runs-on: ${{ matrix.os }} 
    steps:
      - name: Bazel cache
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}

      - uses: actions/checkout@v2

      - name: Test client
        run: bazel test //Maman15/Client/test:all
